
services:
  web:
    build: .
    command: >
      sh -c "python manage.py migrate && daphne -b 0.0.0.0 -p 8000 RadioControl.asgi:application"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
    env_file:
      - .env
  redis:
    image: redis:latest
    ports:
      - "6379:6379"